---
title: "Preparing Figures"
page-layout: full
---

## Figure Preparation checklist

1.  Determine what point you wish to convey with your figure and the most effective way of conveying that point

2.  Remove any extraneous or distracting data that distracts from the main message of your figure

3.  Determine how large the figure needs to be: how much space will it take up on a page?

4.  Will it be easy for your reader to see key details if the figure is this size?

5.  Check that the figure is clear and not pixellated: will your reader be able to see all the important details? Is the resolution good enough?

6.  Check that the colour scheme you have chosen is colour-blind friendly and not visually jarring

7.  Check that any fonts used are legible at the size printed

8.  Figure titles should give a concise "take-home message" conveying the result(s) shown in the figure

9.  Figure legends should give enough detail about the experiment for the reader to understand what was done (the figure should be able to stand on its own)

[Guidance on writing good figure titles and legends (with examples)](./FigureTitleLegend.docx)

## Guides/Important Info for Figure Preparation

-   Refer back to the [Data presentation and figure preparation](https://sipbs-compbiol.github.io/BM432/notebooks/04-data_presentation_workshop.html) (BM432 workshop 6 materials) as needed.

-   [Making model figures](./Making_model_figures_workshop.pptx) (slides for our discussion)

-   [Beyond Bar and Line Graphs: Time for a New Data Presentation Paradigm](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002128)

-   [Read Ten Simple Rules for Better Figures](https://doi.org/10.1371/journal.pcbi.1003833)

-   [Digital Images Are Data: And Should Be Treated as Such](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4210356/)

-   [Ten common statistical mistakes to watch out for when writing or reviewing a manuscript](https://elifesciences.org/articles/48175)

-   [Fundamentals of graphic design---essential tools for effective visual science communication](https://www.facetsjournal.com/doi/10.1139/facets-2018-0049)

-   [11 Graphic Design Tips to Create Images Like a Pro](https://blog.snappa.com/graphic-design-tips/)

## Other Useful Resources

-   [Biorender](https://www.biorender.com/)

-   [ImageJ Basics](https://imagej.nih.gov/ij/docs/pdfs/ImageJ.pdf)

-   [Coblis --- Color Blindness Simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/)

-   [Data visualization with ggplot2 :: Cheat Sheet](https://rstudio.github.io/cheatsheets/html/data-visualization.html?_gl=1*yq93b*_ga*NDg4Mzg2NDQ4LjE2OTI4ODYzNzY.*_ga_2C0WZ1JHG0*MTY5MzIyOTcyMy41LjAuMTY5MzIyOTcyMy4wLjAuMA..)

::: callout-tip
## A few points about specific figure types (a.k.a. some of Morgan's pet peeves)

-   [Why You *Must* Plot Your Growth Data On Semi-log Graph Paper](https://schaechter.asmblog.org/schaechter/2018/07/why-you-must-plot-your-growth-data-on-semi-log-graph-paper.html)

-   Make sure you include a scale on any images that need them (e.g., micrographs, phylogenetic trees)

-   By convention, figure titles and legends are presented **below** the corresponding figure, while table titles are presented **above** the corresponding table.

-   Make sure your text is formatted correctly within your figure (e.g., species names should be italicized, gene and protein names should be formatted correctly)
:::
