---
title: "Project Schedule"
---

The project schedule below is intended as a guide to help you manage your time during your final year honours project. You should feel free to print a copy and edit/modify it as needed to best support your learning needs (for example, by adding additional key dates such as personal project milestones or modifying some of the suggested activities to better fit your schedule and needs).

::: callout-important
You are expected to attend all meetings/group meetings. You should have completed any indicated activities for that meeting (listed in orange "What you should do to prepare"). You should also come prepared with any questions (e.g., about papers you have read, results from your experimental work, general questions about good scientific practices, etc.)
:::

Note that the resources provided (e.g., papers listed in the project descriptor, resources linked for each week) are only intended as a starting point (and should be used in conjunction with the resources presented in the BM432 workshops). You are expected to search the literature independently (this is part of your project performance mark.) You are also strongly encouraged to seek out additional resources to support your learning and development as a researcher (e.g. time management apps/resources, ggplot2 tutorials, additional writing tips/guidance....)

::: callout-tip
You should make certain that you understand the points listed in the green "Comprehension check" for each week and you should read the indicated resources/search the literature/check with Dr. Feeney for further guidance if you are not sure about any point.
:::

::: callout-important
Please be sure to check the BM432 MyPlace page for any updates to official deadlines.
:::

+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| Week      | Week Overview/Activities                                                                                                                                                                                                                                                                                                                           | Meeting Details                                                                                               |
+===========+====================================================================================================================================================================================================================================================================================================================================================+===============================================================================================================+
| 1         | **Suggested activities for this week:**                                                                                                                                                                                                                                                                                                            | **Week 1 Group meeting**                                                                                      |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Begin reading papers listed in the project descriptor                                                                                                                                                                                                                                                                                          | **Time, location, TBD**                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Begin literature search                                                                                                                                                                                                                                                                                                                        | **Meeting agenda**                                                                                            |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-warning appearance="simple"}                                                                                                                                                                                                                                                                                                         | 1.  Introductions                                                                                             |
|           | **What you should do to prepare for the group meeting:**                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 2.  Discuss project description and aims                                                                      |
|           | -   Read the Project expectations and learning agreement documents and note any questions you may have                                                                                                                                                                                                                                             |                                                                                                               |
|           | -   Reread the project descriptor                                                                                                                                                                                                                                                                                                                  | 3.  Project resources -- overview and questions                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 4.  Writing exercise #1                                                                                       |
|           | ::: {.callout-tip appearance="simple"}                                                                                                                                                                                                                                                                                                             |                                                                                                               |
|           | **Comprehension check**                                                                                                                                                                                                                                                                                                                            | 5.  Any questions/AOB                                                                                         |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand the project descriptor and can you identify appropriate keywords to begin your literature search?                                                                                                                                                                                                                            |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you have a plan for reference management and how you will store/organise your notes?                                                                                                                                                                                                                                                        |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Are you aware of the resources offered by the Strathclyde Library for [referencing](https://www.strath.ac.uk/professionalservices/library/researchrevise/referencing/) and [academic practices](https://www.strath.ac.uk/studywithus/strathlife/academicsupport/)?                                                                             |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Have you looked through the list of [suggested resources for project and time management](https://mafeeney.github.io/BM432projects/management.html)?                                                                                                                                                                                           |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 2         | **Suggested activities for this week**                                                                                                                                                                                                                                                                                                             | **Week 2 Group meeting**                                                                                      |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Continue literature search/reading papers                                                                                                                                                                                                                                                                                                      | **Time, location, TBD**                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   As you read, pay attention to how well (or not) papers are written. Take notes on e.g. well-written methods sections in order to better inform your own writing practices                                                                                                                                                                      | **Meeting agenda**                                                                                            |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-warning appearance="simple"}                                                                                                                                                                                                                                                                                                         | 1.  Journal club -- MF to lead paper discussion                                                               |
|           | **What you should do to prepare for the group meeting:**                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 2.  Writing exercise #2                                                                                       |
|           | -   Read the selected journal club paper and note any questions you may have                                                                                                                                                                                                                                                                       |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                | 3.  Explanation of week 3 task (mini-journal club)                                                            |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-tip appearance="simple"}                                                                                                                                                                                                                                                                                                             | 4.  Any questions/AOB                                                                                         |
|           | **Comprehension check:**                                                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand the structure of a scientific paper and know how to critically read one?                                                                                                                                                                                                                                                     |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Are you using appropriate strategies (keywords and filters) for searching the literature? Are there any key papers that you might be missing?                                                                                                                                                                                                  |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   What do you think are some of the unanswered questions in the literature? How does the aim of your project compare with these?                                                                                                                                                                                                                 |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 3         | **Suggested activities for this week**                                                                                                                                                                                                                                                                                                             | **Week 3 Group meeting**                                                                                      |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Continue literature search/reading papers                                                                                                                                                                                                                                                                                                      | **Time, location, TBD**                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Start outlining thesis introduction                                                                                                                                                                                                                                                                                                            | **Meeting agenda**                                                                                            |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-warning appearance="simple"}                                                                                                                                                                                                                                                                                                         | 1.  Mini-journal club -- each student to lead a short discussion of their chosen paper                        |
|           | **What you should do to prepare for the group meeting:**                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 2.  Writing exercise #3                                                                                       |
|           | -   Ask MF to approve paper choice for week 3 journal club                                                                                                                                                                                                                                                                                         |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 3.  Explanation of week 4 task (detailed intro outline)                                                       |
|           | -   Come prepared to lead a mini-discussion of your selected paper                                                                                                                                                                                                                                                                                 |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                | 4.  Any questions/AOB                                                                                         |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-tip appearance="simple"}                                                                                                                                                                                                                                                                                                             |                                                                                                               |
|           | **Comprehension check:**                                                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand what makes a good and useful outline? check out some resources for writing outlines such as [how to outline](https://owl.purdue.edu/owl/general_writing/the_writing_process/developing_an_outline/how_to_outline.html) and [the importance of outlining](https://learningcenters.rutgers.edu/resources/importance-outlining) |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   For your selected paper for our mini journal club: Do you understand the aim of the paper? Can you describe the experimental methods and the results? Are the authors' conclusions supported by the data?                                                                                                                                      |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 4         | **Suggested activities for this week**                                                                                                                                                                                                                                                                                                             | **Week 4 Group meeting**                                                                                      |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Continue literature search/reading papers                                                                                                                                                                                                                                                                                                      | **Time, location, TBD**                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Start outlining thesis introduction/ start writing thesis introduction                                                                                                                                                                                                                                                                         | **Meeting agenda**                                                                                            |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-warning appearance="simple"}                                                                                                                                                                                                                                                                                                         | 1.  Feedback on detailed outlines                                                                             |
|           | **What you should do to prepare for the group meeting:**                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 2.  Discussion of introduction structure and scientific writing (principles of composition)                   |
|           | -   Write a detailed outline for your thesis introduction, and bring this to the group meeting to share                                                                                                                                                                                                                                            |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                | 3.  Writing exercise #4                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-tip appearance="simple"}                                                                                                                                                                                                                                                                                                             | 4.  Explanation of week 5 task (model figure/flow diagram)                                                    |
|           | **Comprehension check:**                                                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 5.  Any questions/AOB                                                                                         |
|           | -   Have you read through, and do you understand, MF's [general writing tips](https://mafeeney.github.io/BM432projects/writingtips.html)?                                                                                                                                                                                                          |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand how to logically structure a paragraph? As you begin to write, are you organising your introduction in a logical way?                                                                                                                                                                                                        |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Are you using a correct citation style?                                                                                                                                                                                                                                                                                                        |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 5         | **Suggested activities for this week**                                                                                                                                                                                                                                                                                                             | **Week 5 Group meeting**                                                                                      |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Continue literature search/reading papers                                                                                                                                                                                                                                                                                                      | **Time, location, TBD**                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Start/continue writing thesis introduction                                                                                                                                                                                                                                                                                                     | **Meeting agenda**                                                                                            |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-warning appearance="simple"}                                                                                                                                                                                                                                                                                                         | 1.  Discussion of model figures and flow diagrams (how, when, and why to use them)                            |
|           | **What you should do to prepare for the group meeting:**                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 2.  Project planning discussion                                                                               |
|           | -   Identify at least one model figure/flow diagram from the papers you have been reading and bring a printed copy to the meeting to discuss                                                                                                                                                                                                       |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                | 3.  Writing exercise #5                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-tip appearance="simple"}                                                                                                                                                                                                                                                                                                             | 4.  Any questions/AOB                                                                                         |
|           | **Comprehension check:**                                                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand the hypothesis and aims of your project? Can you explain these in your own words?                                                                                                                                                                                                                                            |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Have you looked at the Thesis Submission checklist and do you understand how your introduction should be formatted?                                                                                                                                                                                                                            |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand what kind of feedback you can expect on your thesis intro and do you have a plan for how you can act on this feedback?                                                                                                                                                                                                       |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 6-10?     | ::: {.callout-important appearance="simple"}                                                                                                                                                                                                                                                                                                       | **Week 6-9 group meetings**                                                                                   |
|           | **DRAFT** introduction due **DATE**                                                                                                                                                                                                                                                                                                                |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                | **Time, location, TBD**                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | **Experimental work begins**                                                                                                                                                                                                                                                                                                                       | **Meeting agenda**                                                                                            |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | **Suggested activities for these weeks**                                                                                                                                                                                                                                                                                                           | 1.  Discussion of results/progress since the previous meeting                                                 |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Make a detailed plan for how you will execute your experimental work, and discuss this with MF                                                                                                                                                                                                                                                 | 2.  Discuss next steps                                                                                        |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Carry out experimental work for your thesis                                                                                                                                                                                                                                                                                                    | 3.  Writing exercise                                                                                          |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Be sure to record all pertinent details needed for your methods section/begin drafting methods                                                                                                                                                                                                                                                 | 4.  Any questions/AOB                                                                                         |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Read through the feedback on your draft introduction and then contact MF to schedule a meeting to discuss it                                                                                                                                                                                                                                   | **Individual meetings to discuss feedback on draft introductions (week 6-7):** e-mail MF to arrange a meeting |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Begin editing your introduction                                                                                                                                                                                                                                                                                                                |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-warning appearance="simple"}                                                                                                                                                                                                                                                                                                         |                                                                                                               |
|           | **What you should do to prepare for the weekly group meetings:**                                                                                                                                                                                                                                                                                   |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Come prepared to discuss your results from the previous week                                                                                                                                                                                                                                                                                   |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Be prepared to discuss/troubleshoot your experiments                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Think about potential next steps/future experiments                                                                                                                                                                                                                                                                                            |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-tip appearance="simple"}                                                                                                                                                                                                                                                                                                             |                                                                                                               |
|           | **Comprehension check:**                                                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you have a data management plan ready for your project work?                                                                                                                                                                                                                                                                                |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand what details you should be recording in order to [write your methods section](https://mafeeney.github.io/BM432projects/methods.html)? Have you paid attention to the methods sections of relevant papers to see what level of detail is generally required?                                                                  |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand how to prepare a figure for scientific writing? Have you read through MF's figure [preparation checklist](https://mafeeney.github.io/BM432projects/figures.html)?                                                                                                                                                            |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | -   Do you understand what feedback is and how to use feedback to improve your writing?                                                                                                                                                                                                                                                            |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
|           | **Suggested activities for this week**                                                                                                                                                                                                                                                                                                             | **Practice presentation meeting**                                                                             |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | Read MF's [presentation preparation resources](https://mafeeney.github.io/BM432projects/slides.html)                                                                                                                                                                                                                                               | **Time, location, TBD**                                                                                       |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-warning appearance="simple"}                                                                                                                                                                                                                                                                                                         | **Meeting agenda**                                                                                            |
|           | **What you should do to prepare for the meeting:**                                                                                                                                                                                                                                                                                                 |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 1.  Practice presentations and Q&A                                                                            |
|           | -   Prepare a draft of your slides for your project presentation                                                                                                                                                                                                                                                                                   |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    | 2.  Feedback on draft slides                                                                                  |
|           | -   Rehearse your presentation 2-3x (you should have a good idea of what you want to say for each slide                                                                                                                                                                                                                                            |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                | 3.  Any questions/AOB                                                                                         |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | ::: {.callout-tip appearance="simple"}                                                                                                                                                                                                                                                                                                             |                                                                                                               |
|           | **Comprehension check:**                                                                                                                                                                                                                                                                                                                           |                                                                                                               |
|           |                                                                                                                                                                                                                                                                                                                                                    |                                                                                                               |
|           | What questions do you think your audience is likely to ask?                                                                                                                                                                                                                                                                                        |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
|           | ::: {.callout-important appearance="simple"}                                                                                                                                                                                                                                                                                                       |                                                                                                               |
|           | **Powerpoint slides for presentation due** **DATE**                                                                                                                                                                                                                                                                                                |                                                                                                               |
|           | :::                                                                                                                                                                                                                                                                                                                                                |                                                                                                               |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
