---
title: "Science Communication Resources"
page-layout: full
---

## General Science Communication Resources

These are some general resources for students engaging with science communication projects. However, students on other project types may still find them useful (you are, after all, going to want to communicate your science to someone at some point - even if only to write up your thesis and get a good mark for it!)

-   [Science Communication Resources](https://500womenscientists.org/science-communication-resources)

-   [Ten simple rules for scientists engaging in science communication](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011251)

-   [Ten simple rules for drawing scientific comics](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005845)

-   [Ten Simple Rules for Effective Online Outreach](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003906)

-   [How to Eliminate Jargon From Science Communication](https://asm.org/Articles/Policy/2021/October-21/How-to-Eliminate-Jargon-From-Science-Communication)

-   [Writing Survey Questions](https://www.pewresearch.org/our-methods/u-s-surveys/writing-survey-questions/)

## Twine Resources

Resources for students whose projects involve using Twine to create interactive stories/virtual escape rooms/etc. You may also find it useful to look at MF's [virtual escape room github](https://github.com/mafeeney/Virtual-Escape-Rooms) for some examples of coding and how to host a Twine story on GitHub.

-   [Twine](https://twinery.org/)

-   [Twine cookbook](https://twinery.org/cookbook/index.html)

-   [How to use Twine and SugarCube to create interactive adventure games](https://opensource.com/article/18/2/twine-gaming)

-   [A Total Beginner's Guide to Twine 2.](http://www.adamhammond.com/twineguide/)

-   [Harlowe manual](https://twine2.neocities.org/)

-   [Interactive Fiction Community Forum](https://intfiction.org/c/authoring/twine/46) (a forum used by many Twine users, often helpful for troubleshooting code problems)

-   [MF's project demo file](./assets/demo2024-projects.html) (right-click to download this and then import it into Twine to see the code examples)
